name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fbc63b368ded10cc7aba9bdccbeaa92680951beb29e5437d82db8c417f3c410"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
