name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caf79ea3bd51a4671ac1e4c94da75a6413bfe3de548fcf0fc7d52f77c061c537"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
